branches:
  only:
    - master
language: python
python:
  - "3.6"
install: 
  - pip install tox-travis
  - pip install coveralls
matrix:
  include:
    - python: 3.6
      env: TOXENV=lint
script: tox
after_success: coveralls
