language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install: 
  - pip install tox-travis
  - pip install coveralls
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
script: tox
after_success: coveralls
