language: python
python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
install: 
    - pip install -r requirements/test.txt
    - pip install coveralls
    - pip install -e .
script: pytest --cov=omgorm
after_success:
    coveralls
