language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install: 
  - pip install -e .
  - pip install tox-travis
  - pip install coveralls
# before_script:
#   - flake8 .
script: tox
after_success: coveralls
